### ISSUE TITLE
General Rewrite for readability and better code structure?

### ISSUE THREAD

**Issue by fearocanity** [fearocanity/ebtrfio-template#21]
Came up with this idea, Is to designate and arrange functions and much more easier to read...

___
### `scripts/post.sh` file

```bash
(...)
post_comment(){
   # rest of the code is here
   ...
}

# post image to front page
post_fp(){
   # rest of the code is here
   ...
}
```

### `main.sh` file
```bash
(...)
# import functions from and variables from various files that would need to accomplish task
. scripts/post.sh
. secrets.sh
. config.conf

# call functions got from "post.sh" file
post_comment "${token}" "${post_id}" "${message}"
sleep 3
post_fp "${token}" "frame/frame_${??}.jpg" "${message}"
```

Function name would be `<name-of-scriptfile>_<function-name>`
e.g `post_comment()`, And it would take several args needed
Variables must be used inside a function only... `unset` it in the end of the function, or make the variable only available on function using `local`

Functions returns json data, using jq and other text processing _(a separate script handling this)_
### [3] possible exit codes

| Error Code | Description |
|--------|--------|
| 0 | no error |
| 1 | error |
| 2 | no arguments supplied _(only applied when it is needed)_ | 

___
Should we mess with our current code base? What do you think @Rendevior?

**Comment by Rendevior** [comment]
Great, But it would take time...

**Comment by fearocanity** [comment]
Should i create a pr?

**Comment by fearocanity** [comment]
Exit codes still isn't implemented correctly.

**Comment by fearocanity** [comment]
> Exit codes still isn't implemented correctly.

Ill probably open this again when a pr is created for fixing it.
