### ISSUE TITLE
finish/stop the bot when there are no more frames or invalid fb_tok

### ISSUE THREAD

**Issue by JavaRaf** [fearocanity/ebtrfio-template#34]
I noticed that forks/templates that have been stopped for years continue to run every 2 hours, 35 minutes, even if they have no frames to post or valid tok_fb.

I don't understand much about bash, so it will take a long time to make a pull request, so I thought it would be better to open an issue.

**Comment by JavaRaf** [comment]
Possible solutions

Disable init_banner via a curl request if the frameinterator item has not been modified in over a month.

Comment out the trigger line in the yml file and push to the repository

**Comment by fearocanity** [comment]
We could do it like this, when the frame iterator hits the total frame provided in config it would disable the workflow (init_banner)
```diff
if [[ "$(<./frameiterator)" -ge "$(sed -nE 's|.*total_frame="([^"]*)".*|\1|g' ./config.conf)" ]]; then
+  # the api call to disable the workflow
   curl (...)
fi
```

**Comment by JavaRaf** [comment]
Yes, something like that would solve the problem, but I don't know how to do it. So I'll leave it to you
